### ISSUE TITLE
VTK 9: Slicer viewer do not show the Slice

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5220]
Working on the slice view issue, here are some results.

Below are the **Results**  obtained after running the **Test1** and **Test2** in two builds of Slicer, One with VTK8 and one with VTK9.

* VTK8: Slicer/Slicer@d52af6b303
* VTK9: This PR at https://github.com/Slicer/Slicer/pull/5141/commits/47672a73f6442205083b7ede0cd34696b92d652a

# Results

## Summary

| | VTK 8 | VTK 9 |
|---|----|---|
| Test1| :heavy_check_mark:  | :heavy_check_mark: |
| Test2|  :heavy_check_mark:  | :x: |

I suspect the problem is related to the use of [vtkLightBoxRendererManager](https://github.com/commontk/CTK/blob/support-build-with-vtk89/Libs/Visualization/VTK/Core/vtkLightBoxRendererManager.h) in [ctkVTKSliceView](https://github.com/commontk/CTK/blob/support-build-with-vtk89/Libs/Visualization/VTK/Widgets/ctkVTKSliceView.h)

## Outputs

| | VTK 8 | VTK 9 |
|---|----|---|
| Test1| ![image](https://user-images.githubusercontent.com/219043/92126306-04ee6680-edce-11ea-8b9d-da5024824099.png)  | ![image](https://user-images.githubusercontent.com/219043/92126424-28b1ac80-edce-11ea-955e-a5bd7ea0765f.png) |
| Test2|  ![image](https://user-images.githubusercontent.com/219043/92126511-44b54e00-edce-11ea-8f5b-3c4ed85c6ebc.png)  | ![image](https://user-images.githubusercontent.com/219043/92126607-631b4980-edce-11ea-9a48-a796af2e335f.png) |

# Tests

## Test1: Visualize slice pipeline output using vtkDataSetMapper/vtkRenderer/vtkRenderWindow

```python
import vtk
import SampleData

SampleData.downloadSample("MRHead")

sliceLogic = slicer.app.layoutManager().sliceWidget("Red").sliceLogic()
imageData = sliceLogic.GetImageDataConnection().GetProducer().GetOutputDataObject(0)

mapper = vtk.vtkDataSetMapper()

actor = vtk.vtkActor()
actor.SetMapper(mapper)

ren = vtk.vtkRenderer()
renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)
iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

ren.AddActor(actor)

renWin.SetSize(300,300)

mapper.SetInputData(imageData)
renWin.Render()
```

## Test2: Visualize slice pipeline output using ctkSliceView

```python
import ctk
import SampleData

SampleData.downloadSample("MRHead")

sliceLogic = slicer.app.layoutManager().sliceWidget("Red").sliceLogic()
imageDataConnection = sliceLogic.GetImageDataConnection()

sliceView = ctk.ctkVTKSliceView()
sliceView.setImageDataConnection(imageDataConnection)
sliceView.show()
sliceView.forceRender()
```

_Originally posted by @jcfr in https://github.com/Slicer/Slicer/pull/5141#issuecomment-686523379_

**Comment by jcfr** [comment]
@lassoan 

To follow up on https://github.com/Slicer/Slicer/pull/5141#issuecomment-686523379, here is an experiment that I was expecting to fail with VTK9 ... but it works:

```python
import vtk
import SampleData

SampleData.downloadSample("MRHead")

sliceLogic = slicer.app.layoutManager().sliceWidget("Red").sliceLogic()
imageData = sliceLogic.GetImageDataConnection().GetProducer().GetOutputDataObject(0)


renWin = vtk.vtkRenderWindow()

class RendererItem:
  
  def __init__(self, renWin):
    itemRenderer = vtk.vtkRenderer()
    camera = itemRenderer.GetActiveCamera()
    #
    itemRenderer.SetLayer(0)
    #
    itemImageMapper = vtk.vtkImageMapper()
    itemImageMapper.SetColorWindow(255)
    itemImageMapper.SetColorLevel(127.5)
    #
    itemHighlightedBoxActor = vtk.vtkActor2D()
    itemHighlightedBoxActor.SetVisibility(False)
    #
    itemImageActor = vtk.vtkActor2D()
    itemImageActor.SetMapper(itemImageMapper)
    itemImageActor.GetProperty().SetDisplayLocationToBackground()
    itemImageActor.SetVisibility(False)
    #
    itemRenderer.AddActor2D(itemImageActor)
    itemRenderer.AddActor2D(itemHighlightedBoxActor)
    itemRenderer.SetViewport(0.0, 0.0, 1.0, 1.0)
    renWin.AddRenderer(itemRenderer)
    #
    camera = itemRenderer.GetActiveCamera()
    camera.ParallelProjectionOn()
    #
    self.itemRenderer = itemRenderer
    self.itemImageMapper = itemImageMapper
    self.itemHighlightedBoxActor = itemHighlightedBoxActor
    self.itemImageActor = itemImageActor
  
  def setupCornerAnnotation(self):
    cornerAnnotation = vtk.vtkCornerAnnotation()
    cornerAnnotation.SetMaximumLineHeight(0.07)
    #
    tprop = cornerAnnotation.GetTextProperty()
    tprop.ShadowOn()
    self.itemRenderer.AddViewProp(cornerAnnotation)
    #
    cornerAnnotation.ClearAllTexts()
    cornerAnnotation.SetText(2, "Hello")
    self.cornerAnnotation = cornerAnnotation
  
  def setData(self, imageData):
    self.itemImageMapper.SetInputData(imageData)
    self.itemImageMapper.SetZSlice(0)
    self.itemImageActor.SetVisibility(True)
  
  def setHB(self):
    poly = vtk.vtkPolyData()
    points = vtk.vtkPoints()
    #
    shift = 0.0002
    points.InsertNextPoint(0. + shift, 0. + shift, 0)
    points.InsertNextPoint(1. + shift, 0. + shift, 0)
    points.InsertNextPoint(1. + shift, 1. + shift + 0.1, 0)
    points.InsertNextPoint(1. + shift, 1. + shift, 0)
    points.InsertNextPoint(0. + shift, 1. + shift, 0)
    points.InsertNextPoint(0. + shift, 0. + shift - 0.1, 0)
    #
    cells = vtk.vtkCellArray()
    cells.InsertNextCell(6)
    cells.InsertCellPoint(0)
    cells.InsertCellPoint(1)
    cells.InsertCellPoint(2)
    cells.InsertCellPoint(3)
    cells.InsertCellPoint(4)
    cells.InsertCellPoint(5)
    poly.SetPoints(points)
    poly.SetLines(cells)
    #
    coordinate = vtk.vtkCoordinate()
    coordinate.SetCoordinateSystemToNormalizedViewport()
    coordinate.SetViewport(self.itemRenderer)
    #
    polyDataMapper = vtk.vtkPolyDataMapper2D()
    polyDataMapper.SetInputData(poly)
    polyDataMapper.SetTransformCoordinate(coordinate)
    polyDataMapper.SetTransformCoordinateUseDouble(True)
    #
    self.itemHighlightedBoxActor.SetMapper(polyDataMapper)
    self.itemHighlightedBoxActor.GetProperty().SetColor(1, 1, 0.5)
    self.itemHighlightedBoxActor.GetProperty().SetDisplayLocationToForeground()
    self.itemHighlightedBoxActor.GetProperty().SetLineWidth(2.0)
    self.itemHighlightedBoxActor.SetVisibility(True)
    #
    self.poly = poly
    self.coordinate = coordinate
    self.points = points
    self.cells = cells
    self.polyDataMapper = polyDataMapper


item1 = RendererItem(renWin)
item1.setupCornerAnnotation()
item1.setData(imageData)
item1.setHB()

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)

renWin.SetSize(300,300)
renWin.Render()
```

![image](https://user-images.githubusercontent.com/219043/93224174-d44bec80-f73e-11ea-8398-1070f0d7584c.png)

_Originally posted by @jcfr in https://github.com/Slicer/Slicer/pull/5141#issuecomment-692754874_

**Comment by lassoan** [comment]
Thanks a lot, this is very helpful. I'll be able to work on this starting tomorrow afternoon.

**Comment by lassoan** [comment]
I've experimented this a lot and found that the image mapper, renderer, and actor are all set up correctly, because if I take the renderer and add it to a vtkRenderWindow then the slice is displayed correctly. I've removed the lightbox manager and even corner annotations and it did not make any difference. It seems that the vtkImageActor/vtkImageMapper does not work in a QVTKOpenGLNativeWidget. I'll try to reproduce this in a standalone VTK example.

**Comment by Punzo** [comment]
Hi, I just want to report that Slicer-4.13.0-2020-10-07 linux binaries (and also my build with VT9 from source code), on my ubuntu 20.04, does not render the data in the 2D views:

![image](https://user-images.githubusercontent.com/7985338/95444633-50aca680-095e-11eb-89bc-be52c25ffe74.png)

nvidia drivers seems ok and running (version 450.66). Does anyone else can reproduce it?

**Comment by lassoan** [comment]
Yes, we know, we could not figure out yet what causes the issue. It would be awesome if you could give it a try, too. Setting up the same pipeline seems to work in VTK but not in Slicer application.

**Comment by Punzo** [comment]
sorry, maybe I was not clear, for me also Test1 didin't work (while worked for JC), see results (Test1, VTK9):

![image](https://user-images.githubusercontent.com/7985338/95480714-836d9380-098c-11eb-93ed-e3f096e98ca6.png)

I'll give a try to look for the issue.

**Comment by lassoan** [comment]
OK, let us know if you find out anything.

**Comment by jcfr** [comment]
>  will report if it addressed the issue discussed here.

It did not address the issue

**Comment by sankhesh** [comment]
@jcfr @lassoan Its been a while since I looked into the Slicer codebase. Is it possible to do a git bisect with VTK to identify the change that introduced the issue?

**Comment by jcfr** [comment]
> Is it possible to do a git bisect with VTK to identify the change that introduced the issue?

Since we are able to reproduce the problem with CTK, I will try this approach. Thanks for the suggestion.

**Comment by jcfr** [comment]
The faulty  commit is kitware/vtk@2021768f7f1eb07ba19ef06e418f8a042d8b04b5

**Comment by jcfr** [comment]
Update:

The issue happens when enabling the "DisplayLocationToBackground"  on the vtkActor2D used with the vtkImageMapper. 

If I comment the line updating the display location, the image is properly displayed but other actors are not displayed in the front.

**Comment by lassoan** [comment]
Is this DisplayLocationToBackground attribute a legacy thing or still supported? Instead of DisplayLocationToBackground, we may order actors by using layers.

**Comment by sankhesh** [comment]
@lassoan That property is being used to place the image in the camera frustum. I am not sure why that causes the issue described here though. Maybe, the image is getting clipped somehow??

**Comment by jcfr** [comment]
The following minimal example allow to reproduce the problem: https://github.com/jcfr/5220-slicer-rendering-failure-with-VTK9

The associated README.md file provides additional details.

@sankhesh: Would you have any suggestion on how to update the example so that the rendering is working ?

**Comment by jcfr** [comment]
Thanks to @sankhesh, we now have a fix to address this (see https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407?commit_id=750ce4ed11f88412ff6aa4b39cd34031d0ca3fb3)

While it is going through review before it is integrated in upstream VTK, I will proceed with the following:
* integrate the fix into the current [Slicer/VTK@slicer-v9.0.20201013-bc2f5892b3](https://github.com/Slicer/VTK/tree/slicer-v9.0.20201013-bc2f5892b3) branch and commit the change so that we close this issue.
* Then, update Slicer/VTK to the latest VTK9 and also integrate this change.

**Comment by lassoan** [comment]
Awesome! We already know that there are a couple of other serious issues, so probably we should keep the factory using VTK8 until they are resolved: https://github.com/Slicer/Slicer/labels/domain%3Avtk9

**Comment by jcfr** [comment]
> We already know that there are a couple of other serious issues, so probably we should keep the factory using VTK8 until they are resolved

Agreed. I will be working the VTK team to address the other issues.

**Comment by sankhesh** [comment]
@jcfr https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413 is the correct fix for this issue. It would be worth checking to see if that branch fixes the other issues too.

**Comment by sankhesh** [comment]
@lassoan @jcfr Could you also try the changes from https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407 with Slicer?

**Comment by jcfr** [comment]
Re: 7407 and 7413

I will try these and report back in a few. Thanks for the update.

Should I try with both applied at the same time or independently?

**Comment by jcfr** [comment]
Here is the summary:

| Changes | Status | 
|----|-----|
| [750ce4e](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407/diffs?commit_id=750ce4ed11f88412ff6aa4b39cd34031d0ca3fb3) (v1 of [MR-7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407)) | :heavy_check_mark: (addresses only #5220)  |
| [d787bc3](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407/diffs?commit_id=d787bc38f7208d96de1c16874bdfc56539f42981) (v2 of [MR-7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407)) | :x: |
| [e5109ee](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413/diffs?commit_id=e5109ee197fc7e4bf0ddd8679f78b51e01144019) ([MR-7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413))  | :x: |
| [750ce4e](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407/diffs?commit_id=750ce4ed11f88412ff6aa4b39cd34031d0ca3fb3) (v1 of [MR-7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407))  + [e5109ee](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413/diffs?commit_id=e5109ee197fc7e4bf0ddd8679f78b51e01144019) ([MR-7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413)) | :heavy_check_mark: (addresses only #5220)  |
| [d787bc3](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407/diffs?commit_id=d787bc38f7208d96de1c16874bdfc56539f42981) (v2 of [MR-7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407)) + [e5109ee](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413/diffs?commit_id=e5109ee197fc7e4bf0ddd8679f78b51e01144019) ([MR-7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413)) | :x: |

**Comment by sankhesh** [comment]
@jcfr Sorry for the misunderstanding. 

Ideally, [MR - 7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413) fixes the issue with Qt where a images pushed to the far plane were being clipped. That fixes the test application for me and should be the only fix for #5220. I am surprised that Slicer image background rendering is not fixed with this change alone. Could you please double check?

[MR - 7407](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7407) is a better code path for 2D actors in VTK. It essentially removes the Z-coordinate from the equation when placing 2D actors in the view. I just wanted to make sure that it doesn't introduce any other issues in Slicer.

**Comment by jcfr** [comment]
I confirm that only integrating [MR-7413](https://gitlab.kitware.com/vtk/vtk/-/merge_requests/7413) does not fixes the problem.  The test was done using Qt 5.10 on my older linux distribution.

I will test on Windows where I a very recent Qt and report back.

```
* 5c2e793e11 - (HEAD -> slicer-v9.0.20201111-733234c785-v2) [Backport MR-7413] Ensure depth function is GL_LEQUAL in Qt widgets (2 seconds ago) <Sankhesh Jhaveri>
* fcf78cb30c - Revert "[backport MR-7407] Shift the Z value of the 2D vertices when in the background" (59 minutes ago) <Jean-Christophe Fillion-Robin>
* fbfecacef8 - (origin/slicer-v9.0.20201111-733234c785, slicer-v9.0.20201111-733234c785) [backport MR-7407] Shift the Z value of the 2D vertices when in the background (2 days ago) <Sankhesh Jhaveri>
* 7d4474199b - [backport MR-7338] COMP: Associate "all.py" install rule with "python" component (2 days ago) <Jean-Christophe Fillion-Robin>
* 065a176e21 - BUG: Update vtkPythonUtil to disable relative import causing crash for Slicer modules (2 days ago) <Jean-Christophe Fillion-Robin>
* 38048ca4a2 - COMP: Remove FindTBB and expect VTK to be configured with TBB_DIR (2 days ago) <Jean-Christophe Fillion-Robin>
* 0666614a76 - COMP: Remove vtk-m submodule (2 days ago) <Jean-Christophe Fillion-Robin>
*   733234c785 - (kitware/master) Merge branch 'paraview/release' (2 days ago) <Ben Boeckel>
```

**Comment by jcfr** [comment]
>I will test on Windows where I have a very recent Qt and report back.

Same issue on windows. Only integrating MR-7413 does not fix the problem.
